---
- name: Get ARP information
  hosts: all
  gather_facts: false


  tasks:
    - name: show arp
      raw: "show arp"

      register: print_output

    -  debug: var=print_output.stdout_lines


# Commands to run: 
#1) ansible-playbook getarp1.yml -u david -k
#2) Grep for IP address: ansible-playbook getarp1.yml -u david -k | grep '168\.122'